from __future__ import annotations

import json
import os
import webbrowser
from pathlib import Path
from typing import Any, Dict, List, Optional
import nbformat as nbf

from dev_agents.tools.base import tool


@tool(
    name="generate_colab_link",
    description="Generate a 1-click Google Colab URL from a GitHub repository path, Gist ID, or Google Drive ID.",
)
def generate_colab_link(
    github_repo: Optional[str] = "DiveshJ8/dev-agents",
    path: Optional[str] = None,
    branch: str = "main",
    gist_id: Optional[str] = None,
    drive_id: Optional[str] = None,
) -> str:
    """Generates a direct Colab URL for opening notebooks in Google Colab."""
    if gist_id:
        return f"https://colab.research.google.com/gist/{gist_id}"
    elif drive_id:
        return f"https://colab.research.google.com/drive/{drive_id}"
    elif github_repo and path:
        # Standardize path
        clean_path = path.replace("\\", "/").lstrip("/")
        return f"https://colab.research.google.com/github/{github_repo}/blob/{branch}/{clean_path}"
    elif github_repo:
        return f"https://colab.research.google.com/github/{github_repo}"
    else:
        return "https://colab.research.google.com/"


@tool(
    name="create_colab_notebook",
    description="Generate a valid Jupyter/Colab notebook (.ipynb) with optional GPU/TPU accelerator and environment setup cells.",
)
def create_colab_notebook(
    output_path: str,
    title: str,
    cells_json: str,
    accelerator: str = "GPU",
    gpu_type: str = "T4",
    github_repo: str = "DiveshJ8/dev-agents",
) -> str:
    """
    Creates an .ipynb notebook optimized for Google Colab.
    
    Args:
        output_path: Target path for the .ipynb file (e.g. 'notebooks/demo.ipynb')
        title: Title of the notebook
        cells_json: JSON list of dicts with keys 'type' ('code' or 'markdown') and 'content' (string)
        accelerator: 'GPU', 'TPU', or 'None'
        gpu_type: 'T4', 'A100', or 'V100'
        github_repo: GitHub repo for the Open In Colab badge
    """
    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)

    nb = nbf.v4.new_notebook()

    # Colab specific metadata
    colab_metadata: Dict[str, Any] = {
        "colab": {
            "provenance": [],
            "toc_visible": True,
        }
    }
    if accelerator.upper() == "GPU":
        colab_metadata["accelerator"] = "GPU"
        colab_metadata["colab"]["gpuType"] = gpu_type
    elif accelerator.upper() == "TPU":
        colab_metadata["accelerator"] = "TPU"

    nb.metadata.update(colab_metadata)

    # 1. Header with Colab Badge
    badge_url = "https://colab.research.google.com/assets/colab-badge.svg"
    colab_link = generate_colab_link(github_repo=github_repo, path=output_path)
    badge_markdown = (
        f"# {title}\n\n"
        f"[![Open In Colab]({badge_url})]({colab_link})\n\n"
        f"*Notebook generated by Dev-Agents Colab Specialist.*"
    )
    nb.cells.append(nbf.v4.new_markdown_cell(badge_markdown))

    # Parse and append user cells
    try:
        cells_data = json.loads(cells_json) if isinstance(cells_json, str) else cells_json
        for c in cells_data:
            c_type = c.get("type", "code").lower()
            c_content = c.get("content", "")
            if c_type == "markdown":
                nb.cells.append(nbf.v4.new_markdown_cell(c_content))
            else:
                nb.cells.append(nbf.v4.new_code_cell(c_content))
    except Exception as e:
        return f"Error parsing cells_json: {str(e)}"

    with open(target, "w", encoding="utf-8") as f:
        nbf.write(nb, f)

    return (
        f"Successfully created Colab notebook at '{output_path}'.\n"
        f"Colab Launch URL: {colab_link}\n"
        f"Accelerator: {accelerator} ({gpu_type if accelerator == 'GPU' else ''})"
    )


@tool(
    name="package_app_for_colab",
    description="Package an existing Python app (Streamlit, Gradio, FastAPI) into a runnable Colab notebook with public tunneling.",
)
def package_app_for_colab(
    app_filepath: str,
    output_notebook_path: str,
    app_type: str = "gradio",
    port: int = 7860,
    github_repo: str = "DiveshJ8/dev-agents",
) -> str:
    """
    Transforms a local Python app file into a self-contained Google Colab notebook
    that automatically provisions dependencies, starts the app, and exposes a public URL.
    """
    app_path = Path(app_filepath)
    if not app_path.exists():
        return f"Error: App file '{app_filepath}' not found."

    app_code = app_path.read_text(encoding="utf-8")
    app_name = app_path.name
    app_type_lower = app_type.lower()

    cells: List[Dict[str, str]] = []

    # Cell 1: Environment Installation
    if "gradio" in app_type_lower:
        reqs = "!pip install -q gradio"
        run_code = (
            f"%%writefile {app_name}\n"
            f"{app_code}\n\n"
            f"# Run Gradio app with share=True for instant public link\n"
            f"!python {app_name} --share"
        )
    elif "streamlit" in app_type_lower:
        reqs = "!pip install -q streamlit localtunnel"
        run_code = (
            f"%%writefile {app_name}\n"
            f"{app_code}\n\n"
            f"# Run Streamlit in background and tunnel with localtunnel\n"
            f"import urllib.request, time\n"
            f"external_ip = urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip()\n"
            f"print('Your tunnel password / external IP is:', external_ip)\n"
            f"!streamlit run {app_name} & npx localtunnel --port {port}"
        )
    elif "fastapi" in app_type_lower:
        reqs = "!pip install -q fastapi uvicorn pyngrok nest-asyncio"
        run_code = (
            f"%%writefile {app_name}\n"
            f"{app_code}\n\n"
            f"# Expose FastAPI server with ngrok or localtunnel\n"
            f"!uvicorn {app_path.stem}:app --port {port} & npx localtunnel --port {port}"
        )
    else:
        reqs = "!pip install -q torch torchvision torchaudio"
        run_code = (
            f"%%writefile {app_name}\n"
            f"{app_code}\n\n"
            f"!python {app_name}"
        )

    cells.append({"type": "markdown", "content": f"## 1. Install Dependencies for {app_type.upper()}"})
    cells.append({"type": "code", "content": reqs})
    cells.append({"type": "markdown", "content": "## 2. Launch Application & Public Tunnel"})
    cells.append({"type": "code", "content": run_code})

    return create_colab_notebook(
        output_path=output_notebook_path,
        title=f"Run {app_name} on Google Colab",
        cells_json=json.dumps(cells),
        accelerator="GPU",
        github_repo=github_repo,
    )


@tool(
    name="get_colab_local_runtime_command",
    description="Get instructions and command to connect Google Colab directly to your local Jupyter runtime.",
)
def get_colab_local_runtime_command(port: int = 8888) -> str:
    """Returns the exact command to allow Colab web UI to connect to a local execution runtime."""
    cmd = f"jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' --port={port} --NotebookApp.port_retries=0"
    instructions = (
        "### Connecting Google Colab to Local/Remote Runtime\n\n"
        "1. Start the Jupyter server with Colab cross-origin permission enabled:\n"
        f"   ```bash\n   {cmd}\n   ```\n"
        "2. Copy the token URL from the terminal output (e.g. `http://localhost:8888/?token=...`).\n"
        "3. In Google Colab, click the **Connect** button (top right) -> **Connect to a local runtime**.\n"
        "4. Paste your backend URL into the dialog and click **Connect**.\n"
        "5. Your Colab notebook is now executing code directly on your local hardware!"
    )
    return instructions


@tool(
    name="open_colab_in_browser",
    description="Open a Google Colab notebook URL or GitHub notebook path in the default web browser.",
)
def open_colab_in_browser(url_or_path: str, github_repo: str = "DiveshJ8/dev-agents") -> str:
    """Opens a Colab URL or converts a local/repo path to a Colab URL and opens it in the browser."""
    if url_or_path.startswith("http://") or url_or_path.startswith("https://"):
        target_url = url_or_path
    else:
        target_url = generate_colab_link(github_repo=github_repo, path=url_or_path)

    try:
        webbrowser.open(target_url)
        return f"Successfully opened Google Colab in your browser: {target_url}"
    except Exception as e:
        return f"Error opening browser: {str(e)}. Target URL: {target_url}"
